triggers:
- description: null
  envs: []
  last_enabled_at: 2024-06-21T12:39:16+04:00
  name: Retrain models hourly
  pipeline_uuid: automatic_retraining
  schedule_interval: '@hourly'
  schedule_type: time
  settings:
    allow_blocks_to_fail: true
    create_initial_pipeline_run: true
    skip_if_previous_running: true
  sla: null
  start_time: 2024-06-21T12:40:00+04:00
  status: active
  token: null
  variables: {}