{
 "title": "NY-Taxi Model performance Dashboard",
 "time": { "from": "2022-01-31T20:00:00.000Z", "to": "2022-02-28T20:00:00.000Z" },
 "panels": [
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n$__timeGroup(timestamp, '1h') as time,\r\navg(prediction_drift) as prediction_drift\r\nFROM dummy_metrics \r\nWHERE $__timeFilter(timestamp) \r\ngroup by 1\r\norder by 1"
    }
   ]
  },
  {
   "title": "Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(timestamp, '24h') as time,\r\nnum_drifted_columns as  num_drifted_columns\r\nfrom dummy_metrics WHERE $__timeFilter(timestamp) \r\nOrder by 1 "
    }
   ]
  },
  {
   "title": "Mean",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(prediction_drift) FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Share of Missing Values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(timestamp, '24h') as time, \r\nshare_missing_values \r\nFROM dummy_metrics \r\nWHERE $__timeFilter(timestamp) \r\norder BY 1"
    }
   ]
  }
 ]
}